[project]
name = "powergrid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matt Humphrey", email = "mhumphrey9@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=7.3.0",
    "ipython>=9.17.1",
]

[project.scripts]
powergrid = "powergrid:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
